# Generated by Django 6.0.2 on 2026-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='user-profile/default.png', upload_to='user_profile/'),
        ),
    ]
